name: PR

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened]
    branches:
      - main

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  CI: 1
  HUSKY: 0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build js 👷
    timeout-minutes: 45
    needs: [filter]
    if: ${{ needs.filter.outputs.js == 'true' ||  needs.filter.outputs.json == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: "./.github/actions/setup-pnpm"
      - name: Build
        run: pnpm build

  filter:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    outputs:
      js: ${{ steps.changes.outputs.js }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        name: Detect changes
        id: changes
        with:
          filters: |
            js:
              - "**.js"
              - "**.ts"
              - "**.jsx"
              - "**.tsx"

  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.js == 'true' }}
    timeout-minutes: 60
    permissions:
      contents: read
      pull-requests: write
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: "./.github/actions/setup-pnpm"
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

  misspell:
    name: Misspell 🕵️ - reviewdog
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out code.
        uses: actions/checkout@v4
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          reporter: github-pr-review
          exclude: |
            ./core/api/docs/*
